# -*- coding: utf8 -*-

lc_shrygluserCode = 'id = userCode'
lc_shrygluserName = 'id = userName'
lc_shryglcx = 'xpath = //*[@id="dynamic-table_wrapper"]/div[1]/div[2]/label/button'

lc_shryglbtSelectItem = 'xpath = //*[@id="simple-table"]/tbody/tr/td[1]/input'
lc_shrygltp = 'xpath = //*[@id="dynamic-table_wrapper"]/div[4]/div/button[1]'
lc_shryglparentOrgNumberTwo = 'id = parentOrgNumberTwo'
lc_shryglorgNumberTwo = 'id = orgNumberTwo'
lc_shryglrytpqd = 'xpath = //*[@id="changeDepartModel"]/div[1]/div/div[2]/button[1]'
lc_shryglrytpqx = 'xpath = //*[@id="changeDepartModel"]/div[1]/div/div[2]/button[2]'
lc_shrygltpcgqd = 'xpath = /html/body/div[9]/div/div/div[2]/button'
lc_shryglplsc = 'xpath = //*[@id="dynamic-table_wrapper"]/div[4]/div/button[2]'
lc_shryglsccgqd = 'xpath = /html/body/div[8]/div/div/div[2]/button'
lc_shryglxg = 'xpath = //*[@id="simple-table"]/tbody/tr/td[8]/a[1]'
lc_shryglsc = 'xpath = //*[@id="simple-table"]/tbody/tr/td[8]/a[2]'
lc_shryglztqy = 'xpath = //*[@id="simple-table"]/tbody/tr[2]/td[2]/span/label[1]/span'
lc_shryglztty = 'xpath = //*[@id="simple-table"]/tbody/tr[2]/td[2]/span/label[2]/span'
lc_shryglcyfdY = 'xpath = //*[@id="simple-table"]/tbody/tr[3]/td[2]/span/label[1]/span'
lc_shryglcyfdN = 'xpath = //*[@id="simple-table"]/tbody/tr[3]/td[2]/span/label[2]/span'
lc_shryglztqd = 'xpath = //*[@id="auditStaffModel"]/div/div/div[3]/button[1]'
lc_shryglztqx = 'xpath = //*[@id="auditStaffModel"]/div/div/div[3]/button[2]'
lc_shryglszcgqd = 'xpath = /html/body/div[8]/div/div/div[2]/button'
lc_shryglzzjzym = 'xpath = //*[@id="dynamic-table_wrapper"]/div[2]/div[2]/div[2]/div'