# -*- coding:utf8 -*-

lc_khxxglcontractNo = 'id = contractNo'
lc_khxxglcx = 'xpath = //*[@id="dynamic-table_wrapper"]/div[1]/div[1]/div[4]/label/button'
lc_khxxglcheckBox = 'xpath = //*[@id="simple-table"]/tbody/tr[1]/td[1]/label/span'
lc_khxxgldrmbxz = 'xpath = //*[@id="dynamic-table_wrapper"]/div[2]/div/div[1]/a[1]'
lc_khxxgldr = 'xpath = //*[@id="dynamic-table_wrapper"]/div[2]/div/div[1]/a[2]'
lc_khxxgldc = 'xpath = //*[@id="dynamic-table_wrapper"]/div[2]/div/div[1]/a[3]'
lc_khxxglgj = 'xpath = //*[@id="simple-table"]/tbody/tr[1]/td[20]/a[1]'
lc_khxxglxggjr = 'xpath = //*[@id="simple-table"]/tbody/tr[1]/td[20]/a[2]'
lc_khxxglworkUserNames = 'id = workUserNames'
lc_khxxglfpqd = 'xpath = //*[@id="updateFollowModel"]/div/div/div[3]/button[1]'
lc_khxxglfpqx = 'xpath = //*[@id="updateFollowModel"]/div/div/div[3]/button[2]'
lc_khxxglfpcgqd = 'xpath = /html/body/div[9]/div/div/div[2]/button'
lc_khxxgllxdx0 = 'xpath = //*[@id="telRecordForm"]/table/tbody/tr[2]/td[2]/label[1]/span'
lc_khxxgllxdx1 = 'xpath = //*[@id="telRecordForm"]/table/tbody/tr[2]/td[2]/label[2]/span'
lc_khxxgllxdx2 = 'xpath = //*[@id="telRecordForm"]/table/tbody/tr[2]/td[2]/label[3]/span'
lc_khxxglcz0 = 'xpath = //*[@id="telRecordForm"]/table/tbody/tr[2]/td[4]/label[1]/span'
lc_khxxglcz1 = 'xpath = //*[@id="telRecordForm"]/table/tbody/tr[2]/td[4]/label[2]/span'
lc_khxxgllxqk = 'id = contactSituation'
lc_khxxgllxjg = 'id = contactResult'
lc_khxxglremark = 'id = remark'
lc_khxxglczxxbc = 'xpath = //*[@id="main-container"]/div[2]/div/div[2]/div[1]/button'
lc_khxxglczcgqd = 'xpath = /html/body/div[9]/div/div/div[2]/button'
lc_khxxglsl = 'xpath = //*[@id="main-container"]/div[2]/div/div[2]/div[4]/button[1]/i'
