# -*- coding: utf8 -*-

# lc_fdpzproductId = 'id = productId'
# lc_fdpzorgRegionId = 'id = orgRegionId'
# lc_fdpzsaleAreaId = 'id = saleAreaId'
# lc_fdpzareaCompanyId = 'id = areaCompanyId'
# lc_fdpztrialOrg = 'id = trialOrg'
# lc_fdpztrialOrg1 = 'id = trialOrg1'
# lc_fdpzfirstCreditId = 'id = firstCreditId'
# lc_fdpzreviewOrg = 'id = reviewOrg'
# lc_fdpzreviewOrg1 = 'id = reviewOrg1'
# lc_fdpzrepateCreditId = 'id = repateCreditId'
# lc_fdpzpzfdgz = 'xpath = //*[@id="main-container"]/div[2]/div/div[2]/div[1]/div/button'

lc_fdpzproductId = 'xpath = //*[@id="productId_chosen"]/ul/li/input'
lc_fdpzorgRegionId = 'xpath = //*[@id="orgRegionId_chosen"]/ul/li/input'
lc_fdpzsaleAreaId = 'xpath = //*[@id="saleAreaId_chosen"]/ul/li/input'
lc_fdpzareaCompanyId = 'xpath = //*[@id="areaCompanyId_chosen"]/ul/li/input'
lc_fdpztrialOrg = 'id = trialOrg'
lc_fdpztrialOrg1 = 'xpath = //*[@id="trialOrg1_chosen"]/ul/li/input'
lc_fdpzfirstCreditId = 'xpath = //*[@id="firstCreditId_chosen"]/ul/li/input'
lc_fdpzreviewOrg = 'id = reviewOrg'
lc_fdpzreviewOrg1 = 'xpath = //*[@id="reviewOrg1_chosen"]/ul/li/input'
lc_fdpzrepateCreditId = 'xpath = //*[@id="repateCreditId_chosen"]/ul/li/input'
lc_fdpzpzfdgz = 'xpath = //*[@id="main-container"]/div[2]/div/div[2]/div[1]/div/button'