# -*- coding: utf-8 -*-

Locator_fgsywgl = u'link = 分公司业务管理'
Locator_sfxxlr = u'link = 身份信息录入'
Locator_dqrsqjxf = u'link = 待确认申请件-消分'
Locator_sqxxlr = u'link = 申请信息录入'
Locator_rhdc = u'link = 入户调查'
Locator_ywjdcx = u'link = 业务进度查询'
Locator_fgsycqy = u'link = 分公司远程签约'
Locator_fgsxxqy = u'link = 分公司线下签约'
Locator_khbgsq = u'link = 卡号变更申请'
Locator_sqjcxfgs = u'link = 申请件查询-分公司'
Locator_khbgcx = u'link = 卡号变更查询'
Locator_yhkjbcx = u'link = 银行卡解绑查询'
Locator_khjlhhmd = u'link = 客户经理灰黑名单'
Locator_dhtxjlcxfgs = u'link = 电话提醒记录查询-分公司'
Locator_ddhtxkh = u'link = 带电话提醒客户'
Locator_fgskkyy = u'link = 分公司扣款预约'
Locator_fgskkgl = u'link = 分公司扣款管理'
Locator_jjcc = u'link = 进件查重'
Locator_fgsfxcx = u'link = 分公司风险查询'
Locator_drjqkh = u'link = 当日结清客户'
Locator_yysrzjgcxfgs = u'link = 运营商认证结果查询-分公司'

Locator_zbxsywgl = u'link = 总部信审业务管理'
Locator_zbys = u'link = 总部预审'
Locator_czfd = u'link = 重置分单'
Locator_shrygl = u'link = 审核人员管理'
Locator_shfd = u'link = 审核分单'
Locator_zbcs = u'link = 总部初审'
Locator_zbfs = u'link = 总部复审'
Locator_xgzt = u'link = 修改状态'
lc_xgztgetClient = 'id = getClient'
Locator_fdpz = u'link = 分单配置'

Locator_zbyygl = u'link = 总部运营管理'
Locator_xgztjsb = u'link = 修改状态-技术部'
Locator_qyfh = u'link = 签约复核'
Locator_sqjfk = u'link = 申请件放款'
Locator_khbgsh = u'link = 卡号变更审核'
Locator_sqjcxzb = u'link = 申请件查询总部'
Locator_ddhtxzbkf = u'link = 待电话提醒-总部客服'
Locator_ddtxjlcx = u'link = 电话提醒记录查询'
Locator_fhshrygl = u'link = 复核审核人员管理'
Locator_fhshfd = u'link = 复核审核分单'
Locator_qyhtcs = u'link = 签约回退初审'
Locator_qyhtfs = u'link = 签约回退复审'
Locator_yysrzjgcx = u'link = 运营商认证结果查询'
Locator_fsdxzbkf = u'link = 发送短信-总部客服'
Locator_tdhtztcx = u'link = 团贷合同状态查询'

Locator_fxglzx = u'link = 风险管理中心'
Locator_sqjcx = u'link = 申请件查询'

Locator_dxywgl = u'link = 电销业务管理'
Locator_khxxgl = u'link = 客户信息管理'
Locator_dxxxcx = u'link = 电销信息查询'
Locator_yxkhcx = u'link = 意向客户查询'
Locator_dxrygl = u'link = 电销人员管理'
Locator_fdgl = u'link = 分单管理'
Locator_xhdyxgl = u'link = 循环贷营销管理'
Locator_yxjcx = u'link = 营销件查询'
Locator_xhdsqjcx = u'link = 循环贷申请件查询'

Locator_xtgl = u'link = 系统管理'
Locator_jggl = u'link = 机构管理'
Locator_yhgl = u'link = 用户管理'

Locator_cwgl = u'link = 财务管理'
Locator_jkrzhxxcx = u'link = 借款人账户信息查询'

Locator_zjgl = u'link = 资金管理'
Locator_wylspp = u'link = 网银流水匹配'
Locator_wylsppcx = u'link = 网银流水匹配查询'

Locator_tkgl = u'link = 退款管理'
Locator_tksq = u'link = 退款申请'
Locator_tkcx = u'link = 退款查询'

Locator_tqjqgl = u'link = 提前结清管理'
Locator_khtqjqsq = u'link = 客户提前结清申请'
Locator_khtqjqcx = u'link = 客户提前结清查询'

Locator_clz = 'xpath = //*[@id="main-mask-id"]/div/i'